---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-k8s-pv02 
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 800Gi

