---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: synology-k8s-pv02
spec:
  capacity:
    storage: 5000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: synology
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: synology.home
    path: "/volume2/k8s-pv02"
