---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology
  resources:
    requests:
      storage: 5000Gi
